//! Helpers for authenticating yt-dlp using the stored YouTube session.
//! Writes cookies to a Netscape-format temp file (avoids the `--add-header "cookie:..."`
//! deprecation) and returns a fresh `authorization` SAPISIDHASH header.

use std::io::Write;
#[cfg(unix)]
use std::os::unix::fs::OpenOptionsExt;

/// Result of preparing yt-dlp auth arguments.
pub struct YtDlpAuth {
    /// Path to a temp file containing cookies in Netscape format.
    /// Call [`cleanup_cookie_file`] after the yt-dlp command finishes.
    pub cookie_path: std::path::PathBuf,
    /// Extra `--add-header` pairs (without the cookie header).
    pub extra_headers: Vec<(String, String)>,
}

impl Drop for YtDlpAuth {
    fn drop(&mut self) {
        let _ = std::fs::remove_file(&self.cookie_path);
    }
}

/// Load the stored YouTube session, write cookies to a temp file, and return
/// the cookie path plus extra auth headers (with a freshly computed SAPISIDHASH).
///
/// Returns `None` when no session is stored (anonymous mode).
pub fn prepare_ytdlp_auth() -> Option<YtDlpAuth> {
    let headers_json = crate::utils::secure_storage::load_youtube_headers()
        .map_err(|e| log::debug!("Could not load YouTube headers: {e}"))
        .ok()
        .flatten()?;

    let map: serde_json::Map<String, serde_json::Value> = serde_json::from_str(&headers_json)
        .map_err(|e| log::debug!("Failed to parse headers JSON: {e}"))
        .ok()?;

    let cookie_str = map.get("cookie").and_then(|v| v.as_str())?;

    // 1. Write cookies to a temp file (Netscape format)
    let cookie_path = write_netscape_cookies(cookie_str)?;

    // 2. Build extra headers with fresh SAPISIDHASH
    let mut extra: Vec<(String, String)> = Vec::new();

    // Re-compute authorization just like auth.rs does for HTTP requests
    if let Some(sapisid) = extract_sapisid_from_cookie(cookie_str) {
        let timestamp = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_secs())
            .unwrap_or(0);
        let auth_value = sapisidhash(timestamp, &sapisid);
        extra.push(("authorization".to_string(), auth_value));
    }

    // Pass through other non-cookie headers (x-goog-authuser, user-agent, origin, etc.)
    for (key, value) in &map {
        if key.eq_ignore_ascii_case("cookie") || key.eq_ignore_ascii_case("authorization") {
            continue;
        }
        if let Some(val_str) = value.as_str() {
            extra.push((key.clone(), val_str.to_string()));
        }
    }

    // Ensure a user-agent is always set
    if !extra
        .iter()
        .any(|(k, _)| k.eq_ignore_ascii_case("user-agent"))
    {
        extra.push((
            "user-agent".to_string(),
            "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Doremi/2".to_string(),
        ));
    }

    Some(YtDlpAuth {
        cookie_path,
        extra_headers: extra,
    })
}

/// Write a semicolon-joined cookie string to a temp file in Netscape format.
/// BF0.3: uses 0o600 permissions and a random unpredictable name (not pid-based).
fn write_netscape_cookies(cookie_str: &str) -> Option<std::path::PathBuf> {
    use rand::RngExt;
    let dir = std::env::temp_dir();
    // Generate a random 16-char hex suffix to prevent symlink attacks.
    let suffix: String = {
        let mut rng = rand::rng();
        (0..16).map(|_| format!("{:x}", rng.random::<u8>())).collect()
    };
    let filename = format!("doremi_cookies_{}.txt", suffix);
    let path = dir.join(filename);

    // BF0.3: open with mode 0o600 so other users cannot read the session cookies.
    #[cfg(unix)]
    let file_result = std::fs::OpenOptions::new()
        .write(true)
        .create(true)
        .truncate(true)
        .mode(0o600)
        .open(&path);

    #[cfg(not(unix))]
    let file_result = std::fs::OpenOptions::new()
        .write(true)
        .create(true)
        .truncate(true)
        .open(&path);

    let mut file = file_result
        .map_err(|e| log::warn!("Failed to create temp cookie file: {e}"))
        .ok()?;

    // Netscape cookie file header
    writeln!(file, "# Netscape HTTP Cookie File").ok()?;
    writeln!(file, "# Generated by Doremi for yt-dlp").ok()?;

    // YouTube cookies: we don't have domain/path/expiry from a raw cookie header,
    // so we use sensible defaults that yt-dlp/YouTube accept.
    let far_future = 4_100_000_000u64; // ~2100

    for part in cookie_str.split(';') {
        let part = part.trim();
        if let Some(eq_idx) = part.find('=') {
            let name = part[..eq_idx].trim();
            let value = part[eq_idx + 1..].trim();
            writeln!(
                file,
                ".youtube.com\tTRUE\t/\tTRUE\t{}\t{}\t{}",
                far_future, name, value
            )
            .ok()?;
        }
    }

    Some(path)
}

/// Extract SAPISID from a semicolon-joined cookie string (same logic as auth.rs).
fn extract_sapisid_from_cookie(cookie_val: &str) -> Option<String> {
    let mut sapisid = None;
    let mut secure_1 = None;
    let mut secure_3 = None;

    for part in cookie_val.split(';') {
        let part = part.trim();
        if let Some(eq_idx) = part.find('=') {
            let name = part[..eq_idx].trim();
            let val = part[eq_idx + 1..].trim().replace('"', "");
            if name == "__Secure-3PAPISID" {
                secure_3 = Some(val);
            } else if name == "__Secure-1PAPISID" {
                secure_1 = Some(val);
            } else if name == "SAPISID" {
                sapisid = Some(val);
            }
        }
    }

    secure_3.or(secure_1).or(sapisid)
}

/// Compute the SAPISIDHASH authorization value (same logic as auth.rs).
fn sapisidhash(timestamp: u64, sapisid: &str) -> String {
    use sha1::{Digest, Sha1};
    let origin = "https://music.youtube.com";
    let message = format!("{} {} {}", timestamp, sapisid, origin);
    let mut hasher = Sha1::new();
    hasher.update(message.as_bytes());
    format!("SAPISIDHASH {}_{:x}", timestamp, hasher.finalize())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Read;

    #[test]
    fn test_extract_sapisid() {
        assert_eq!(
            extract_sapisid_from_cookie("__Secure-3PAPISID=\"hello\""),
            Some("hello".to_string())
        );
        assert_eq!(
            extract_sapisid_from_cookie("foo=bar; SAPISID=world; baz=qux"),
            Some("world".to_string())
        );
        assert_eq!(extract_sapisid_from_cookie("foo=bar; baz=qux"), None);
    }

    #[test]
    fn test_write_netscape_cookies() {
        let path = write_netscape_cookies("SAPISID=secret; SID=abc123").unwrap();
        let mut content = String::new();
        std::fs::File::open(&path)
            .unwrap()
            .read_to_string(&mut content)
            .unwrap();
        assert!(content.contains(".youtube.com\tTRUE\t/\tTRUE"));
        assert!(content.contains("\tSAPISID\tsecret"));
        assert!(content.contains("\tSID\tabc123"));
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn test_sapisidhash() {
        let hash = sapisidhash(1_700_000_000, "secret-sapisid");
        assert!(hash.starts_with("SAPISIDHASH 1700000000_"));
        assert_eq!(hash.len(), 63);
    }
}
